/**
 * @fileoverview gRPC-Web generated client stub for arm_face_id
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.25.1
// source: face.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.arm_face_id = require('./face_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.arm_face_id.FaceRpcClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.arm_face_id.FaceRpcPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.arm_face_id.RecognitionRequest,
 *   !proto.arm_face_id.RecognitionResponse>}
 */
const methodDescriptor_FaceRpc_RpcRecognizeFace = new grpc.web.MethodDescriptor(
  '/arm_face_id.FaceRpc/RpcRecognizeFace',
  grpc.web.MethodType.UNARY,
  proto.arm_face_id.RecognitionRequest,
  proto.arm_face_id.RecognitionResponse,
  /**
   * @param {!proto.arm_face_id.RecognitionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.arm_face_id.RecognitionResponse.deserializeBinary
);


/**
 * @param {!proto.arm_face_id.RecognitionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.arm_face_id.RecognitionResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.arm_face_id.RecognitionResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.arm_face_id.FaceRpcClient.prototype.rpcRecognizeFace =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/arm_face_id.FaceRpc/RpcRecognizeFace',
      request,
      metadata || {},
      methodDescriptor_FaceRpc_RpcRecognizeFace,
      callback);
};


/**
 * @param {!proto.arm_face_id.RecognitionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.arm_face_id.RecognitionResponse>}
 *     Promise that resolves to the response
 */
proto.arm_face_id.FaceRpcPromiseClient.prototype.rpcRecognizeFace =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/arm_face_id.FaceRpc/RpcRecognizeFace',
      request,
      metadata || {},
      methodDescriptor_FaceRpc_RpcRecognizeFace);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.arm_face_id.RegistrationRequest,
 *   !proto.arm_face_id.RegistrationResponse>}
 */
const methodDescriptor_FaceRpc_RpcRegisterFace = new grpc.web.MethodDescriptor(
  '/arm_face_id.FaceRpc/RpcRegisterFace',
  grpc.web.MethodType.UNARY,
  proto.arm_face_id.RegistrationRequest,
  proto.arm_face_id.RegistrationResponse,
  /**
   * @param {!proto.arm_face_id.RegistrationRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.arm_face_id.RegistrationResponse.deserializeBinary
);


/**
 * @param {!proto.arm_face_id.RegistrationRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.arm_face_id.RegistrationResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.arm_face_id.RegistrationResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.arm_face_id.FaceRpcClient.prototype.rpcRegisterFace =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/arm_face_id.FaceRpc/RpcRegisterFace',
      request,
      metadata || {},
      methodDescriptor_FaceRpc_RpcRegisterFace,
      callback);
};


/**
 * @param {!proto.arm_face_id.RegistrationRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.arm_face_id.RegistrationResponse>}
 *     Promise that resolves to the response
 */
proto.arm_face_id.FaceRpcPromiseClient.prototype.rpcRegisterFace =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/arm_face_id.FaceRpc/RpcRegisterFace',
      request,
      metadata || {},
      methodDescriptor_FaceRpc_RpcRegisterFace);
};


module.exports = proto.arm_face_id;

